[CmdletBinding()]
param(
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]]$CodexArgs
)

$projectRoot = $PSScriptRoot
$envFile = Join-Path $projectRoot '.env'
$proxyPath = Join-Path $PSScriptRoot 'verboo-responses-proxy.mjs'
$fallbackCatalogPath = Join-Path $PSScriptRoot 'verboo.json'

# Dedicated, git-ignored runtime folder. All Codex state (sqlite/logs/sessions)
# and the regenerated catalog live here, so the adapter never pollutes the
# folder it is installed in and never touches a user's existing .codex/config.
$runtimeDir = Join-Path $projectRoot 'codex-verboo-runtime'
New-Item -ItemType Directory -Path $runtimeDir -Force | Out-Null
$catalogPath = Join-Path $runtimeDir 'verboo.json'
$configPath = Join-Path $runtimeDir 'config.toml'

if (-not $env:VERBOO_API_KEY -and (Test-Path -LiteralPath $envFile)) {
  foreach ($line in Get-Content -LiteralPath $envFile) {
    if ($line -match '^\s*VERBOO_API_KEY\s*=\s*(.+?)\s*$') {
      $env:VERBOO_API_KEY = $matches[1].Trim('"', "'")
      break
    }
  }
}

if (-not $env:VERBOO_API_KEY) {
  throw 'VERBOO_API_KEY is not set. Add it to .env (which is ignored by Git) or set it for this shell session.'
}

# Write the provider config into the runtime folder (CODEX_HOME) at launch.
$configText = @(
  '# Generated by codex-verboo. This file lives in the git-ignored runtime folder.'
  "[model_providers.verboo]"
  "name = " + [char]34 + "Verboo Code (local Responses adapter)" + [char]34
  "base_url = " + [char]34 + "http://127.0.0.1:4319/v1" + [char]34
  "env_key = " + [char]34 + "VERBOO_API_KEY" + [char]34
  "wire_api = " + [char]34 + "responses" + [char]34
  "request_max_retries = 1"
  "stream_max_retries = 1"
  "stream_idle_timeout_ms = 7200000"
) -join [Environment]::NewLine
[System.IO.File]::WriteAllText($configPath, $configText, [System.Text.UTF8Encoding]::new($false))

$listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, 0)
$listener.Start()
$port = ([System.Net.IPEndPoint]$listener.LocalEndpoint).Port
$listener.Stop()

$proxyProcess = Start-Process -FilePath 'node' -ArgumentList @($proxyPath, '--port', $port) -PassThru -NoNewWindow
try {
  $ready = $false
  for ($attempt = 0; $attempt -lt 30; $attempt++) {
    Start-Sleep -Milliseconds 100
    try {
      $health = Invoke-RestMethod -Uri "http://127.0.0.1:$port/health" -Method Get -TimeoutSec 1
      if ($health.status -eq 'ok') { $ready = $true; break }
    } catch {
      if ($proxyProcess.HasExited) { throw 'The Verboo Codex adapter exited before it became ready.' }
    }
  }
  if (-not $ready) { throw 'Timed out while starting the Verboo Codex adapter.' }

  # Fetch the live model catalog (all models for the key). Retry a few times;
  # if it still fails, fall back to the committed verboo.json so Codex starts.
  $catalogJson = $null
  for ($attempt = 0; $attempt -lt 3; $attempt++) {
    try {
      $catalogJson = Invoke-RestMethod -Uri "http://127.0.0.1:$port/catalog" -Method Get -TimeoutSec 20
      break
    } catch {
      Write-Warning "Could not fetch the live model catalog (attempt $($attempt + 1)/3): $($_.Exception.Message)"
      if ($attempt -lt 2) { Start-Sleep -Seconds 1 }
    }
  }
  if ($catalogJson -and $catalogJson.models.Count -gt 0) {
    [System.IO.File]::WriteAllText($catalogPath, ($catalogJson | ConvertTo-Json -Depth 10), [System.Text.UTF8Encoding]::new($false))
  } else {
    Write-Warning 'Using the committed model catalog (verboo.json) because the live catalog is unavailable.'
    $catalogPath = $fallbackCatalogPath
  }

  # Plan-adaptive default: deepseek-v4-flash when available, else first model.
  $defaultModel = 'deepseek-v4-flash'
  try {
    $defaultModel = (Invoke-RestMethod -Uri "http://127.0.0.1:$port/catalog/default-model" -Method Get -TimeoutSec 10).default_model
  } catch {
    Write-Warning "Could not resolve the default model ($($_.Exception.Message)); using 'deepseek-v4-flash'."
  }
  Write-Host "Verboo Codex adapter ready - default model: $defaultModel (use /model to switch)"

  $env:CODEX_HOME = $runtimeDir
  & codex `
    -c "model_catalog_json='$catalogPath'" `
    -c "model='$defaultModel'" `
    -c "model_provider='verboo'" `
    -c "model_providers.verboo.base_url='http://127.0.0.1:$port/v1'" `
    -c "model_providers.verboo.name='Verboo Code (local Responses adapter)'" `
    @CodexArgs
  exit $LASTEXITCODE
} finally {
  if ($proxyProcess -and -not $proxyProcess.HasExited) {
    Stop-Process -Id $proxyProcess.Id -Force
  }
}